---
title: "Out-migration"
author: "Zyrashae Smith-Onyewu"
date: "2026-02-27"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())

library(here)
library(readr)
library(dplyr)
library(readxl)
library(stringr)
library(tidycensus)
library(tigris)
library(ggplot2)
library(sf)
library(leaflet)

knitr::opts_knit$set(root.dir = normalizePath("C:/Users/zyras/Documents/GitHub/out_migration"))
options(tigris_use_cache = FALSE, tigris_download_protocol = "HTTP")

```


```{r Load data}

hd2024 <- read_csv("data/sources/hd2024.csv")
ace <- read_csv("data/sources/@additional/ace-institutional-classifications.csv")
data <- left_join(hd2024, ace, by = c("UNITID" = "unitid"))
X2025_HSILists <- read_excel("data/sources/@additional/2025_HSILists.xlsx")

```


```{r Select variables}
# select variables and create a dataset for analysis
data <- data %>% select(LONGITUD, LATITUDE, 
                          UNITID, INSTNM, 
                          CITY, STABBR, ZIP, ICLEVEL, DEGGRANT, HBCU, TRIBAL, 
                          CBSA, CBSATYPE, CSA, COUNTYCD, COUNTYNM, 
                          CONTROL, INSTCAT,
                          `Institutional Classification`, `Student Access and Earnings Classification`)
#Q. Why don't we use 'CARNEGIEIC' or 'CARNEGIESAEC' variables in IPEDS?

# create HSI status variable
data <- X2025_HSILists %>% 
  select(INSTNM, HSI) %>% 
  right_join(data, by = c("INSTNM")) %>% 
  mutate(HSI = if_else(is.na(HSI), 0, HSI))

```


```{r Rename data}
# rename variables
data <- data |> rename(instnm = INSTNM, 
                       hsi = HSI, 
                       longitude = LONGITUD, 
                       latitude = LATITUDE,
                       unitid = UNITID, city = CITY, stabbr = STABBR, zip = ZIP,
                       iclevel = ICLEVEL, deggrant = DEGGRANT, hbcu = HBCU, tribal = TRIBAL,
                       cbsa = CBSA, cbsatype = CBSATYPE, csa = CSA, countycd = COUNTYCD,
                       countynm = COUNTYNM, control = CONTROL, instcat = INSTCAT,
                       c_level = `Institutional Classification`, 
                       c_seaclass = `Student Access and Earnings Classification`) |> 
                select(unitid, instnm, city, stabbr, countycd, countynm, cbsa, cbsatype, csa, 
                       zip,longitude, latitude, 
                       control, iclevel, instcat, deggrant, c_level, c_seaclass,
                       hbcu, hsi, tribal)

```


```{r Clean variables}
# clean and recode Carnegie classification variables
data <- data |> 
  mutate(c_level = case_when(
      c_level == "Mixed Associate Small" ~ 1,
      c_level == "Mixed Associate Medium" ~ 2,
      c_level == "Mixed Associate Large" ~ 3,
      c_level == "Mixed Associate/Baccalaureate" ~ 4,
      c_level == "Mixed Baccalaureate" ~ 5,
      c_level == "Mixed Undergraduate/Graduate-Master's Small" ~ 6,
      c_level == "Mixed Undergraduate/Graduate-Master's Large/Medium" ~ 7,
      c_level == "Mixed Undergraduate/Graduate-Doctorate Small" ~ 8,
      c_level == "Mixed Undergraduate/Graduate-Doctorate Medium" ~ 9,
      c_level == "Mixed Undergraduate/Graduate-Doctorate Large" ~ 10,
      is.na(c_level) ~ -1,
      str_detect(c_level, "^Special") ~ -9,
      str_detect(c_level, "^Professions") ~ -8)) %>% 
  mutate(c_seaclass = case_when(
    c_seaclass == "Higher Access, Lower Earnings" ~ 1,
    c_seaclass == "Higher Access, Medium Earnings" ~ 2,
    c_seaclass == "Opportunity Colleges and Universities-Higher Access, Higher Earnings" ~ 3,
    c_seaclass == "Lower Access, Lower Earnings" ~ 4,
    c_seaclass == "Lower Access, Medium Earnings" ~ 5,
    c_seaclass == "Lower Access, Higher Earnings" ~ 6,
    is.na(c_seaclass) ~ -1,
    c_seaclass == "Not Classified" ~ -2)) |> 
  #data |> count(c_level) |> count(c_seaclass)
  filter(iclevel != -3 & iclevel != 3)

#Turning non desired variables into NA
data <- data |>
    mutate(instcat = ifelse(instcat == 1, NA, instcat), 
           instcat = ifelse(instcat == -1, NA, instcat), 
           instcat = ifelse(instcat == -2, NA, instcat), 
           #instcat = ifelse(instcat %n% c(-2, -1, 1), NA, instcat),
           control = ifelse(control == 3, NA, control), 
           #control = ifelse(control %n% c(-1, 3), NA, control),
           csa = ifelse(csa == -2, NA, csa), 
           cbsatype = ifelse(cbsatype == -2, NA, cbsatype))

```



```{r Import census and ACS variables}

cbsa <- core_based_statistical_areas(cb = FALSE, 
                     year = 2024,
                     refresh = TRUE) 


census <- get_acs(geography = "cbsa",
                  year = 2024,
                  variables = c("B01003_001E", # Total population
                                "DP02_0068PE", # % bach or higher
                                               #ADD MEDIAN INCOME
                                "DP03_0119PE", # % below poverty
                                "B03002_003E", # total white (alone, not hispanic)
                                "B03002_004E", # total black (alone, not hispanic)
                                "B03002_012E", # total hispanic
                                               #ADD PERCENT ASIAN
                                "B03002_001E" #total by ethnicity
                  ),
                  output = "wide") 

analytic_sample <- left_join(cbsa %>% 
                           select(-NAME),
                         census, by = "GEOID")

x <- analytic_sample |>
  mutate(perc_white = B03002_003E/B03002_001E*100,
         perc_black = B03002_004E/B03002_001E*100,
         perc_hisp = B03002_012E/B03002_001E*100,
         perc_bach = coalesce(DP02_0068PE, DP02PR_0068PE),
         tot_pop = B03002_001E*100/100000,
         pop_sqmile = B01003_001E/(ALAND/2.59e+6)) |> # sq meters to sq miles |> 
  select(GEOID, NAME,  
         perc_white, perc_black, perc_hisp,
         perc_commute_transit = DP03_0021PE, 
         perc_novehicle = DP04_0058PE, 
         perc_poverty = DP03_0119PE, 
         perc_bach, tot_pop, pop_sqmile)

y <- data %>% 
  left_join(x %>% 
              mutate(GEOID = as.numeric(GEOID)), 
            by = c("cbsa" = "GEOID"))

analytic_sample <- y

rm(x, y)

```


#Need to fill maps based on whether the CBSA includes a sample postsecondary institution
```{r Map CBSAs}


usmap <- counties(cb = TRUE, resolution = "20m") %>% 
  filter() %>% 
  shift_geometry()

analytic_sf <- st_as_sf(analytic_sample, coords = c("longitude", "latitude"), crs = 4269) %>% 
  filter(cbsa != -2)

x <- analytic_sf %>% 
  select(cbsa, cbsatype, geometry) %>% 
  distinct()


ggplot() +
  geom_sf(data = usmap, aes(), alpha = 0) +
  geom_sf(data = shift_geometry(x),
          aes(),
          fill = "navy")+
  theme_void()

```


```{r Map institutions}

leaflet() %>% 
  addTiles() %>% 
  addMarkers(data = analytic_sf,
             popup = paste(analytic_sf$NAME, "<br>",
                           analytic_sf$instnm))

```

