---
title: MLCA
author: Hyevin Shin
format: pdf
---

```{r setup}
## ---------------------------
##' [libraries]
## ---------------------------

library(tidyverse)
library(readxl)
library(tidycensus)
library(multilevLCA)
library(psych)
library(tigris)
library(nnet)
library(VGAM)
library(gt)
library(car)


rm(list = ls())
```


```{r data}
## ---------------------------
##' [IPEDS/Carnegie Classification Data]
## ---------------------------

# load IPEDS data and merge with the Carnegie Classification

ipeds24 <- read_csv("../data/sources/hd2024.csv")
ipeds_cost <- read_csv("../data/sources/cost1_2024.csv")
#ipeds_schoolsize <- read_csv("../data/sources/ef2024a.csv") #enrollment Fall 2024
carnegie <- read_excel("../data/sources/2025-Public-Data-File.xlsx", sheet = 2)
ic2024 <- read_csv("../data/sources/ic2024.csv")
sfa <- read_csv("../data/sources/sfa2324.csv")
adm <- read_csv("../data/sources/adm2024.csv")
enroll <- read_csv("../data/sources/effy2024.csv") %>%
  filter(EFFYALEV == 3) %>%  #degree/certificate-seeking undergraduates
  select(UNITID, EFFYALEV, EFYTOTLT, EFYAIANT, EFYBKAAT, EFYNHPIT, EFYWHITT, EFYHISPT, EFYASIAT) 
#ipeds_distance <- read_csv("../data/sources/effy2024_dist.csv") %>% 
#  filter(EFFYDLEV == 2) %>%  #undergrad total
#  select(UNITID, EFFYDLEV, EFYDETOT, EFYDEEXC)
ipeds_dist <- read_csv("../data/sources/ef2024a_dist.csv") |> 
  filter(EFDELEV == 2) |>    #undergrad total
  select(UNITID, EFDELEV, EFDETOT, EFDEEXC, XEFDEEXC)
ipeds_learner <- read_csv("../data/sources/ef2024b.csv") |> 
  filter(LSTUDY == 2, EFBAGE %in% c(1, 7)) |>     #undergrad total / all age categories total, age 25 and over total
#number of institutions (= UNITID): 2,487
  select(UNITID, EFBAGE, EFAGE06, EFAGE09) |> 
  pivot_wider(names_from = EFBAGE, 
              values_from = c(EFAGE06, EFAGE09))


#Let's replace this with the size variable in IPEDS (instsize)
# ipeds_schoolsize <- ipeds_schoolsize |> 
#     filter(EFALEVEL == 1) |> #Level of student (1 == all students total)
#     select(UNITID, EFTOTLT) |> #Grand total
#     mutate(size = case_when(
#       EFTOTLT <= 3000 ~ 0,  #small
#       EFTOTLT <= 10000 ~ 1,  #medium
#       EFTOTLT > 10000 ~ 2, #large
#       TRUE ~ NA_real_))

carnegie <- carnegie |> 
  select(unitid, hsi)

# merge files
data <- ipeds24 %>% 
  left_join(carnegie, by = c("UNITID" = "unitid")) %>% 
  left_join(ipeds_cost, by = "UNITID") |> 
  #left_join(ipeds_schoolsize, by = "UNITID") %>%
  left_join(ic2024, by = "UNITID" ) %>%
  left_join(sfa, by = "UNITID") %>%
  left_join(adm, by = "UNITID") %>%
  left_join(enroll, by = "UNITID") |> 
  left_join(ipeds_dist, by = "UNITID") |> 
  left_join(ipeds_learner, by = "UNITID")



# select variables and create a dataset for analysis
x <- data |> 
    rename_all(tolower) |> #converts all column names in a data frame to lowercase
    select(unitid, instnm, city, stabbr, fips, countycd, countynm, cbsa, cbsatype, csa, obereg,
           locale, zip, longitud, latitude, 
           control, iclevel, instcat, deggrant, instsize,
           hloffer,
           carnegieic, carnegiesaec, carnegiealf, carnegieapm, carnegiersch,
           hbcu, hsi, tribal,
           room, relaffil, distnced, athassoc,
           admssn, applcn, openadmp, loan_a, tuition1, upgrntp, 
           efytotlt, efyaiant, efybkaat, efynhpit, efywhitt, efyhispt, efyasiat,
           efdelev, efdetot, efdeexc, xefdeexc, slo7, efage06_1, efage06_7, efage09_1, efage09_7)

# assign to "data"
data <- x


```


```{r Create Sample}
x <- data %>% 
  filter(fips <= 56) |>                                 # Keep only 50 states and DC
  filter(cbsa != -2) |>                                 # Remove colleges not located in CBSAs 
  # filter(!is.na(control), control != 3) |>            # 3: private for-profit
  filter(!is.na(iclevel), iclevel != 3) |>              # 3: less than 2 years
  filter(!is.na(carnegiealf), carnegiealf != 6) %>%     # 6: graduate-focused
  filter(instcat >= 2 & instcat <= 4)                   # 1: degree-granting, graduate with no undergraduate degrees
                                                        # 5-6: non-degree-granting
  #filter(carnegieapm == 1)                             # Keep only colleges classified as "mixed" undergraduate programs
  

data <- x

```


```{r cleaning}
## ---------------------------
##' [Data Cleaning]
## ---------------------------

x <- data |> 
  mutate(
         public = case_when(
            control == 2 ~ 0,                             # 0: private
            control == 1 ~ 1,                             # 1: public 
            control == 3 ~ 2,                             # 2: for-profit
            TRUE ~ NA_real_),   
         
         twoyear = case_when(
            iclevel == 1 ~ 0,                             # 0: 4 or more
            iclevel == 2 ~ 1,                             # 1: at least 2 & less than 4
            TRUE ~ NA_real_),     
         
         # msi = case_when(                                 # 0: non of them
         #    hbcu == 1 ~ 1,                                # 1: HBCU
         #    hsi == 1 ~ 2,                                 # 2: HSI
         #    tribal == 1 ~ 3,                              # 3: TCU
         #    hbcu == 2 & hsi == 0 & tribal == 2 ~ 0,
         #    is.na(hbcu) | is.na(hsi) | is.na(tribal) ~ NA_real_,
         #    TRUE ~ NA_real_),
         
         msi = case_when(
           hbcu == 1 | hsi == 1 | tribal == 1 ~ 1, 
           TRUE ~ 0),
         
         rurality = case_when(
            locale %in% c(31,32,33,41,42,43) ~ 0,         # 0: Town + Rural
            locale %in% c(21,22,23) ~ 1,                  # 1: Suburb
            locale %in% c(11,12,13) ~ 2,                  # 2: City
            TRUE ~ NA_real_),        
         
         size = case_when(
           instsize == 1 ~ 0,                             # 0: < 1,000
           instsize == 2 ~ 1,                             # 1: 1,000 - 4,999
           instsize == 3 ~ 2,                             # 1: 5,000 - 9,999
           instsize == 4 ~ 3,                             # 2: 10,000 - 19,999
           instsize == 5 ~ 4,                             # 3: >=20,000
           TRUE ~ NA_real_),
         
#         tuition = case_when(
#           tuition1 == 0 & obereg != 0 ~ NA_real_,
#           tuition1 == 0 & obereg == 0 ~ 0,
#           tuition1 < 10000 ~ 0,                           # 0: < $10,000          - 1334
#           tuition1 >= 10000 & tuition1 < 20000 ~ 1,       # 1: $10,000 - $19,999  - 689
          # tuition1 >= 20000 & tuition1 < 30000 ~ 2,      # 2: $20,000 - $29,999
#           tuition1 >= 20000 & tuition1 < 40000 ~ 2,       # 3: $30,000 - $39,999  - 531
          # tuition1 >= 40000 & tuition1 < 50000 ~ 4,      # 4: $40,000 - $49,999
#           tuition1 >= 40000                    ~ 3,       # 5: > $50,000          - 384
#           TRUE ~ NA_real_),                               #                       - 316

#         tuitionnn = ntile(tuition1, 4) - 1,               # 0~3: quartiles

#check missing values: sum(is.na(ipeds_cost$TUITION1))  [1] 2,368 (= about 40% of the sample)

         housing = case_when(
           room == 2 ~ 0,                                 # 0: no housing
           room == 1 ~ 1,                                 # 1: offer housing
           TRUE ~ NA_real_),    

         religious = ifelse(relaffil == -2, 0, 1),        # 0: no religious
                                                          # 1: any religious
         
        #We need to remove colleges that offer completely distance education from our sample
         distance = case_when(
           distnced == 2 ~ 0,                             # 0: not completely distanced learning
           distnced == 1 ~ 1,                             # 1: completely distanced learning
           TRUE ~NA_real_),    

         online_perc = case_when(
            is.na(efdetot) ~ NA_real_,
            is.na(efdeexc) & xefdeexc == "A" ~ 0,         # "A": not applicable
            is.na(efdeexc) ~ NA_real_,                    # other missing cases
            TRUE ~ efdeexc / efdetot),

#         online = case_when(
#            is.na(online_perc) ~ NA_real_,
#            online_perc == 0 ~ 0,                         # none                        - 860
#            online_perc < 0.25 ~ 1,                       # more than 0%, less than 25% - 1588
#            online_perc < 0.50 ~ 2,                       # 25% to less than 50%        - 717
#            online_perc <= 1 ~ 3,                         # 50% to 100%                 - 288
#            TRUE ~ NA_real_),                             # NA                          - 11

        online = ntile(online_perc, 4) - 1,               # 0~3: quartiles

#check missing values: sum(is.na(ipeds_dist$EFDETOT))  [1] 0

        evening = case_when(
          slo7 == 0 ~ 0,                                  # 0: no weekend/evening courses
          slo7 == 1 ~ 1,                                  # 1: allows classes only on weekends or only in evenings
          TRUE ~ NA_real_),

#check missing values: sum(is.na(ic2024$SLO7))  [1] 0
        
#        adult_perc = case_when(
#            is.na(efage09_7) ~ NA_real_,
#            is.na(efage09_1) ~ NA_real_,
#            TRUE ~ efage09_7 / efage09_1),
        
#        adult_perc = case_when(
#            is.na(efage09_7) ~ NA_real_,
#            is.na(efage09_1) ~ NA_real_,
#            TRUE ~ efage09_7 / efage09_1),

#        adult = ntile(adult_perc, 4) - 1,                 # 0~3: quartiles

#check missing values: sum(is.na(ipeds_learner$EFAGE09_1))  [1] 0
#check missing values: sum(is.na(ipeds_learner$EFAGE09_7))  [1] 9

#        parttime_perc = case_when(
#            is.na(efage06_1) ~ NA_real_,
#            is.na(efage09_1) ~ NA_real_,
#            TRUE ~ efage06_1 / efage09_1),

#        parttime = case_when(
#            is.na(parttime_perc) ~ NA_real_,
#            parttime_perc == 0 ~ 0,                       # none                        - 73
#            parttime_perc < 0.25 ~ 1,                     # more than 0%, less than 25% - 828
#            parttime_perc < 0.50 ~ 2,                     # 25% to less than 50%        - 344
#            parttime_perc <= 1 ~ 3,                       # 50% to 100%                 - 769
#            TRUE ~ NA_real_),                             # NA                          - 1450

#         parttime = ntile(parttime_perc, 4) - 1,          # 0~3: quartiles        
#check missing values: sum(is.na(ipeds_learner$EFAGE06_1))  [1] 0

         sports = case_when(
           athassoc == 2 ~ 0,                             # 0: not a member
           athassoc == 1 ~ 1,                             # 1: member of National Athletic Association
           TRUE ~NA_real_),

         loan = case_when(
           is.na(loan_a) ~ NA_real_,
           loan_a <= quantile(loan_a, 0.25, na.rm = TRUE) ~ 0,     # 0: lowest
           loan_a <= quantile(loan_a, 0.50, na.rm = TRUE) ~ 1,     # 1: low 
           loan_a <= quantile(loan_a, 0.75, na.rm = TRUE) ~ 2,     # 2: high
           TRUE ~ 3),                                              # 3: highest
 
# Q. Since MLCA requires variables starting at 0, is it appropriate to divide loan amount into quartiles (0–3)?

         asc = case_when(
           carnegiesaec == 2 ~ 0,                         # 0: Higher Access, Lower Earnings 
           carnegiesaec == 4 ~ 1,                         # 1: Higher Access, Medium Earnings
           carnegiesaec == 6 ~ 2,                         # 2: Higher Access, Higher Earnings
           carnegiesaec == 1 ~ 3,                         # 3: Lower Access, Lower Earnings
           carnegiesaec == 3 ~ 4,                         # 4: Lower Access, Medium Earnings
           carnegiesaec == 5 ~ 5,                         # 5: Lower Access, Higher Earnings
           TRUE ~ NA_real_),

         awardlev = case_when(
           carnegiealf %in% c(1,2) ~ 0,                    # 0: associates 
           carnegiealf == 3 ~ 1,                            # 1: baccalaureate
           carnegiealf == 4 ~ 2,                           # 2: undergrad / grad-Master's
           carnegiealf == 5 ~ 3,                           # 3: undergrad / grad-Doctorate 
           
           is.na(carnegiealf) & (hloffer == 3 | hloffer == 4) ~ 0,
           carnegiealf == -2 & (hloffer == 3 | hloffer == 4) ~ 0,
           hloffer == 5 & instcat == 2 ~ 1,
           
           TRUE ~ NA_real_),
         #Check: x %>% filter(is.na(awardlev)) %>% View()

         focus = case_when(
            carnegieapm == -2                          ~ 0,  # 0: Not classified
            carnegieapm == 1                           ~ 1,  # 1: Mixed
            carnegieapm == 2                           ~ 2,  # 2: Professions-focused
            carnegieapm == 3                           ~ 3,  # 3: Applied and career studies
            carnegieapm %in% c(4,5)                    ~ 4,  # 4: Arts and sciences
            carnegieapm == 6                           ~ 5,  # 5: Business
            carnegieapm %in% c(8,9,10)                 ~ 6,  # 6: Medical sciences/health
            carnegieapm == 11                          ~ 7,  # 7: STEM
            carnegieapm == 12                          ~ 8,  # 8: Theology
            TRUE ~ NA_real_),                         
        
        research = case_when( 
            carnegiersch == -2 ~ 0,                   #0: No research designation
            carnegiersch == 3 ~ 1,                    #1: Research Colleges and Universities 
            carnegiersch == 2 ~ 2,                    #2: High Spending
            carnegiersch == 1 ~ 3,                    #3: Very High Spending  
            TRUE ~ NA_real_),          
         
         cbsa = as.character(cbsa),
         cbsatype = as.character(cbsatype),


        pell = case_when(
          upgrntp < 10                   ~ 0,
          upgrntp >= 10 & upgrntp < 30   ~ 1,
          #upgrntp >= 20 & upgrntp < 30   ~ 2,
          upgrntp >= 30 & upgrntp < 50   ~ 2,
         # upgrntp >= 40 & upgrntp < 50   ~ 4,
          upgrntp >= 50                  ~ 3,
          TRUE ~ NA_real_)
          
       )


data <- x |>
  filter(distance == 0) %>%                       # remove observations with only distance education
  group_by(cbsa) %>% 
  mutate(inst_num = n_distinct(unitid),
         inst_num = as.numeric(inst_num)) %>% 
  ungroup() %>% 
  mutate(admrate = admssn/applcn) %>% 
  # mutate(admrate = if_else(openadmp == 1, 1, admrate)) |> 
  mutate(selectivity = case_when(
         openadmp == 1 ~ 0,
         admrate == 1 ~ 0,                        #0: open 
         admrate >= 0.75 & admrate < 1 ~ 1,       #1: less selective
         admrate >= 0.40 & admrate < 0.75 ~ 2,    #2: selective
         admrate < 0.40 ~ 3,                      #3: more selective
         TRUE ~ NA_real_),
         
         i_perc_black = efybkaat/efytotlt,              #Percent of degree-seeking undergrads by race/ethnicity
         i_perc_white = efywhitt/efytotlt,
         i_perc_hisp = efyhispt/efytotlt,
         i_perc_nhpi = (efyaiant + efynhpit)/efytotlt,
         i_perc_asian = efyasiat/efytotlt,
         i_perc_nonwhite = 1 - i_perc_white,
         nonwhite = ntile(i_perc_nonwhite, 4),
         nonwhite = nonwhite - 1
         ) %>% 
  rename(region = obereg) %>% 
  mutate(cbsa = as.character(cbsa))
  
```


```{r}
z <- read_csv("../data/sources/effy2024.csv") %>% 
  filter(EFFYLEV == 2 | EFFYLEV == 4) %>% 
  select(UNITID, EFFYALEV, EFYTOTLT) %>% 
  mutate(EFFYALEV = if_else(EFFYALEV == 2, "undergrad", "grad")) %>% 
  pivot_wider(id_cols = "UNITID",
              names_from = EFFYALEV, 
              values_from = EFYTOTLT) %>% 
  mutate(total_pop = undergrad + grad,
         per_undergrad = undergrad/total_pop,
         per_grad = grad/total_pop)
```




```{r census/ACS data}
## ---------------------------
## [Census/ACS Data]
## ---------------------------

land_area <- core_based_statistical_areas(
  cb = TRUE, 
  year = 2024) %>% 
  select(GEOID, ALAND)


census <- get_acs(geography = "cbsa",
                  year = 2024,
                  variables = c("B01003_001E", # Total population
                                "B19013_001E", # Median Household Income in the Past 12 Months
                                "DP03_0119PE", # % families below poverty line
                                "DP03_0005PE", # % unemployed over 16 years old
                                "DP02_0068PE", # % bach or higher
                                "B03002_003E", # total white (alone, not hispanic)
                                "B03002_004E", # total black (alone, not hispanic)
                                "B03002_012E", # total hispanic
                                "B03002_006E", # total asian (alone, not hispanic)
                                "B03002_001E"  # total by ethnicity
                  ),
                  output = "wide") %>% 
  left_join(land_area)


census <- census |>
  mutate(perc_white = B03002_003E/B03002_001E*100,
         perc_black = B03002_004E/B03002_001E*100,
         perc_hisp = B03002_012E/B03002_001E*100,
         perc_asian = B03002_006E/B03002_001E*100,
         tot_pop = B01003_001E/100000,
         pop_density = B01003_001E/(ALAND/2589988.10)) |> #population per sq mile
  rename(perc_ba = DP02_0068PE,
         med_income = B19013_001E,
         perc_pov = DP03_0119PE,
         perc_unemployed = DP03_0005PE) |> 
  select(tot_pop, pop_density, perc_ba,
         med_income, perc_pov, perc_unemployed,
         perc_white, perc_black, perc_hisp, perc_asian,
         GEOID) |> 
  mutate(GEOID = as.character(GEOID))

data <- data |>
  left_join(census, by = c("cbsa" = "GEOID"))

```


```{r Explore dataset}

data_mlca <- data %>% 
  select(unitid, instnm, stabbr, cbsa, cbsatype, region,  
         public, twoyear, size, rurality, 
         awardlev, 
         religious, focus, housing, research, msi,
         inst_num, selectivity, pell, online, evening, #adult, tuitionnn, parttime,
         tot_pop, pop_density, perc_ba, med_income, perc_pov, perc_unemployed,
         perc_white, perc_black, perc_hisp, perc_asian,
         i_perc_white, i_perc_black, i_perc_hisp, i_perc_asian, nonwhite) %>% 
  as.data.frame()

#metropolitan, tuition,msi, distance,sports,research, 

describe(data_mlca)

x <- data_mlca %>% 
  drop_na() %>% 
  group_by(cbsa) %>% 
  mutate(
    cbsa_id = cur_group_id()
  ) %>% 
  as.data.frame()

# data_mlca %>% anti_join(x, by = "unitid") %>% View()

data_mlca <- x

write_rds(data_mlca, "../data/analytic_v2")

```


```{r MCLA setup}

# Variables:
#   Y-        Columns with indicator variables for level 1 class membership (predictors of institution-level classes)
                # public, two_year, size, msi, award level, research, selectivity 
              
#   iT-       Number of lower-level latent classes

#   id_high-  Name of column with higher-level id
                # CBSA

#   iM-       Number of higher-level latent classes

#   Z-        Columns with lower-level covariates (predictors of level 1 class membership)
                # rurality, housing, religious, sports

#   Zh-       Columns with higher-level covariates (predictors of level 2 class membership)
                # Variables- region, number of IHEs, total population, percent bachelors degree, median income, percent poverty, percent white, percent black, percent hispanic, percent asian


# Level-1 indicators: Observed institution characteristics used to define the latent institution classes
# Level-1 covariates: Institution-level predictors that explain class membership
# Level-2 covariates: CBSA-level regional variables that explain differences in institution class probabilities across regions


# Lower-level indicators based on framework for insitutional diversity in: 
# Harris, M.S. An Empirical Typology of the Institutional Diversity of U.S. Colleges and Universities. Innov High Educ 45, 183–199 (2020). https://doi.org/10.1007/s10755-019-09494-6

#indicators
Y <- c(
  #systemic- structural and governance characteristics
  "public", "size", #"twoyear",
  
  #programmatic- degree level and academic disciplinary offerings
  "awardlev", "focus", "research",
  
  #procedural- how programs are offered and implemented (Harris included % of students enrolled in distance-only classes, and we include that in this analysis)
            #-the institution / management? operation?
  "online",  #ADD VARIABLE FOR THE PERCENTAGE OF STUDENTS WHO ARE EXCLUSIVELY ENROLLED IN ONLINE COURSES
             #categorized share of undergraduates enrolled exclusively in distance education
  "evening",
#  "tuitionnn",
#(1)including tuition as quartiles: iT= 8 & iM= 2            (#obs = 1779)
#(2)including tuition & parttime quartiles: iT= 8 & iM= 2    (#obs = 1779)
  
  #constituential- "student demographics, background, preparation, and abilities" (Harris, 2020 p.187)
  "selectivity", "pell", "msi", "nonwhite" #, "adult", "parttime"
  ) #level-1 indicators 

Z <- c("i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian", "housing", "rurality", "religious")       #level-1 covariates   "sports", 

Zh <- c("cbsatype", "inst_num", "tot_pop", "pop_density", "perc_ba", "med_income", "perc_pov", "perc_unemployed", "perc_white", "perc_black", "perc_hisp", "perc_asian")   #level-2 covariates  "metropolitan", "region", 



```

```{r multicollinearity}
# Level-1 indicators (Y)
## cf. these are not predictors, so technically we don't need to check for multicollinearity here
## cf. these are categorical variables, so VIF may not be appropriate
y_data <- data_mlca |> select(all_of(Y))

set.seed(1234)
y_data$dummy_y <- rnorm(nrow(y_data))

vif_y_model <- lm(dummy_y ~ ., data = y_data)
vif(vif_y_model)


# Level-1 covariates (Z)
z_data <- data_mlca |>  
  select(all_of(Z))

set.seed(1234)
z_data$dummy_y <- rnorm(nrow(z_data))

vif_z_model <- lm(dummy_y ~ ., data = z_data)
vif(vif_z_model)


# Level-2 covariates (Zh)
zh_data <- data_mlca |>  
  select(all_of(Zh)) |>  
  mutate(cbsatype = as.factor(cbsatype))   # switch nominal variable to factor

zh_data$dummy_y <- rnorm(nrow(zh_data))

vif_zh_model <- lm(dummy_y ~ ., data = zh_data)
vif(vif_zh_model)


```


```{r}

set.seed(1234)

model_selection <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 6:12,
  Z              = Z,
  iM             = 2:6,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

analytic_model <- model_selection

analytic_model
```


# ```{r}
set.seed(1234)

# testing 8 lower-level classes, 2 higher-level clusters
test_l8_h2<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 8,
  Z              = Z,
  iM             = 2,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# testing 9 lower-level classes, 2 higher-level clusters
test_l9_h2<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 9,
  Z              = Z,
  iM             = 2,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# testing 10 lower-level classes, 2 higher-level clusters
test_l10_h2<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 10,
  Z              = Z,
  iM             = 2,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# testing 11 lower-level classes, 2 higher-level clusters
test_l11_h2<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 11,
  Z              = Z,
  iM             = 2,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# testing 8 lower-level classes, 3 higher-level clusters
test_l8_h3<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 8,
  Z              = Z,
  iM             = 3,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# testing 9 lower-level classes, 3 higher-level clusters
test_l9_h3<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 9,
  Z              = Z,
  iM             = 3,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

# NO SOLUTION FOUND
# # testing 10 lower-level classes, 3 higher-level clusters
# test_l10_h3<- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 10,
#   Z              = Z,
#   iM             = 3,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )


# testing 11 lower-level classes, 3 higher-level clusters
test_l11_h3 <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 11,
  Z              = Z,
  iM             = 3,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

# testing 8 lower-level classes, 4 higher-level clusters
test_l8_h4 <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 8,
  Z              = Z,
  iM             = 4,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

# NO SOLUTION FOUND
# # testing 9 lower-level classes, 4 higher-level clusters
# test_l9_h4<- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 9,
#   Z              = Z,
#   iM             = 4,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )


# testing 10 lower-level classes, 4 higher-level clusters
test_l10_h4<- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 10,
  Z              = Z,
  iM             = 4,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


# NO SOLUTION FOUND
# # testing 11 lower-level classes, 4 higher-level clusters
# test_l11_h4<- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 11,
#   Z              = Z,
#   iM             = 4,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )


# NO SOLUTION FOUND
# # testing 8 lower-level classes, 5 higher-level clusters
# test_l8_h5 <- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 8,
#   Z              = Z,
#   iM             = 5,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )

# NO SOLUTION FOUND
# # testing 9 lower-level classes, 5 higher-level clusters
# test_l9_h5 <- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 9,
#   Z              = Z,
#   iM             = 5,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )

# NO SOLUTION FOUND
# # testing 10 lower-level classes, 5 higher-level clusters
# test_l10_h5 <- multiLCA(
#   data = data_mlca,
#   Y              = Y,
#   iT             = 10,
#   Z              = Z,
#   iM             = 5,
#   id_high        = c("cbsa_id"),
#   Zh             = Zh,
#   incomplete     = FALSE,
#   extout         = TRUE,
#   verbose        = TRUE,
#   sequential     = TRUE,
#   reord          = FALSE
# )


# testing 11 lower-level classes, 5 higher-level clusters
test_l11_h5 <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 11,
  Z              = Z,
  iM             = 5,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


test_l8_h2
test_l9_h2
test_l10_h2
test_l11_h2

test_l8_h3
test_l9_h3
#test_l10_h3
test_l11_h3

test_l8_h4
#test_l9_h4
test_l10_h4
#test_l11_h4

#test_l8_h5
#test_l9_h5
#test_l10_h5
test_l11_h5


```


# ```{r}

set.seed(1234)

#Single-level LCA without covariates
test_1 <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 6:12,
  # Z              = Z,
  # iM             = 2:5,
  # id_high        = c("cbsa_id"),
  # Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)


#Single-level LCA with covariates
test_1c <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 6:12,
  Z              = Z,
  # iM             = 2:5,
  # id_high        = c("cbsa_id"),
  # Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

test_1
test_1c

summary(test_1)
summary(test_1c)



#Full multilevel analysis with covariates
final_model <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 6:12,
  Z              = Z,
  iM             = 2:5,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)



final_model
summary(final_model)
plot(final_model)


```




```{r level 1 post-estimation}

l1_proportions <- as.data.frame(analytic_model$mPi)  #	Lower-level class proportions given the higher-level latent classes and the covariates

l1_proportions

l1_probabilities <- as.data.frame(analytic_model$mPhi)




```


```{r level 2 predicted classes}

l2_posterior <- as.data.frame(analytic_model$mPW)


l2_classes <- data.frame(
  group_id = row.names(analytic_model$mPW),
  L2_Predicted_Class = apply(l2_posterior, 1, which.max),
  L2_Prob_Class1 = l2_posterior[, 1],
  L2_Prob_Class2 = l2_posterior[, 2],
  L2_Prob_Class3 = l2_posterior[, 3]
)


l2_class_data <- data_mlca %>%
  mutate(cbsa_id = as.character(cbsa_id)) %>% 
  left_join(l2_classes, 
            by = c("cbsa_id" = "group_id")) 

l2_class_summary <- l2_class_data %>% 
  select(cbsa, L2_Predicted_Class ) %>% 
  distinct()

inst_cbsa_classification <- l2_class_data


```



```{r Save data}

write_csv(inst_cbsa_classification, "../data_paper2/inst_cbsa_classification.csv")

```



<!-- ```{r} -->

<!--  #Predicted lower-level class conditional on institutional characteristics -->
<!-- # predicted_class <- multinom( "awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian",data = lc_l2) -->

<!-- data_mlca$.row_id <- seq_len(nrow(data_mlca)) -->

<!-- optimal_model <- multiLCA( -->
<!--   data = data_mlca, -->
<!--   Y              = c("public", "twoyear", "size", "msi", -->
<!--        "research", "selectivity", "focus", -->
<!--        "rurality", "housing", "religious"), -->
<!--   iT             = 9, -->
<!--   Z              = c("awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian"), -->
<!--   iM             = 4, -->
<!--   id_high        = c("cbsa_id"), -->
<!--   Zh             = c("region", "metropolitan", "inst_num", "tot_pop", "pop_density", "perc_ba", "med_income", "perc_pov", "perc_unemployed", "perc_white", "perc_black", "perc_hisp", "perc_asian"), -->
<!--   incomplete     = FALSE, -->
<!--   extout         = TRUE, -->
<!--   verbose        = TRUE, -->
<!--   sequential     = TRUE, -->
<!--   reord          = FALSE, -->
<!--   dataout        = TRUE -->
<!-- ) -->


<!-- ``` -->



<!-- ```{r Multinomial logistic regression} -->

<!-- reg_data <- as.data.frame(optimal_model[["mPW_N"]]) %>%  -->
<!--   mutate(pred_class2 = case_when( -->
<!--     G1 == pmax(G1, G2, G3, G4) ~ "G1", -->
<!--     G2 == pmax(G1, G2, G3, G4) ~ "G2", -->
<!--     G3 == pmax(G1, G2, G3, G4) ~ "G3", -->
<!--     G4 == pmax(G1, G2, G3, G4) ~ "G4"), -->
<!--     class_prob = case_when( -->
<!--       pred_class2 == "G1" ~ G1, -->
<!--       pred_class2 == "G2" ~ G2, -->
<!--       pred_class2 == "G3" ~ G3, -->
<!--       pred_class2 == "G4" ~ G4, -->
<!--     )) %>%  -->
<!--   select(cbsa_id, G1, G2, G3, G4, pred_class2, class_prob) %>%  -->
<!--   distinct() %>%  -->
<!--   select(cbsa_id, pred_class2, class_prob) %>%  -->
<!--   right_join(data_mlca, by = "cbsa_id") -->

<!-- reg_model <- vglm(pred_class2 ~ region + metropolitan + inst_num + tot_pop + pop_density + perc_ba + med_income + perc_pov + perc_unemployed + perc_white + perc_black + perc_hisp + perc_asian, -->
<!--               data = reg_data, -->
<!--               family = multinomial(refLevel = 1)) -->

<!-- summary(reg_model) -->

<!-- coef_vec <- coef(reg_model)                 # vector of all coefficients -->
<!-- vc       <- vcov(reg_model)                 # full covariance matrix -->
<!-- se_vec   <- sqrt(diag(vc))              # standard errorscoef_vec <- coef(model)                 # vector of all coefficients -->
<!-- vc       <- vcov(reg_model)                 # full covariance matrix -->
<!-- se_vec   <- sqrt(diag(vc))              # standard errors -->


<!-- apa_table <- data.frame( -->
<!--   term     = names(coef_vec), -->
<!--   estimate = coef_vec, -->
<!--   SE       = se_vec, -->
<!--   z        = coef_vec / se_vec, -->
<!--   p        = 2 * (1 - pnorm(abs(coef_vec / se_vec))), -->
<!--   OR       = exp(coef_vec), -->
<!--   CI_low   = exp(coef_vec - 1.96 * se_vec), -->
<!--   CI_high  = exp(coef_vec + 1.96 * se_vec) -->
<!-- ) %>% -->
<!--   mutate( -->
<!--     estimate = round(estimate, 3), -->
<!--     SE       = round(SE, 3), -->
<!--     z        = round(z, 2), -->
<!--     p        = round(p, 3), -->
<!--     OR       = round(OR, 3), -->
<!--     CI       = paste0("[", round(CI_low, 3), ", ", round(CI_high, 3), "]") -->
<!--   ) %>% -->
<!--   select(term, estimate, SE, z, p, OR, CI) -->

<!-- apa_table -->

<!-- apa_gt <- apa_table %>% -->
<!--   gt() %>% -->
<!--   cols_label( -->
<!--     term     = "Predictor", -->
<!--     estimate = "B", -->
<!--     SE       = "SE", -->
<!--     z        = "z", -->
<!--     p        = "p", -->
<!--     OR       = "OR", -->
<!--     CI       = "95% CI" -->
<!--   ) %>% -->
<!--   tab_options( -->
<!--     table.font.size = 12, -->
<!--     data_row.padding = px(2), -->
<!--     table.width = pct(80), -->
<!--     column_labels.font.weight = "bold" -->
<!--   ) -->

<!-- apa_gt -->

<!-- ``` -->

