---
title: MLCA
author: Hyevin Shin
format: html
---

```{r setup}
## ---------------------------
##' [libraries]
## ---------------------------

library(tidyverse)
library(readxl)
library(tidycensus)
library(multilevLCA)
library(psych)
library(tigris)
library(nnet)

rm(list = ls())
```


```{r data}
## ---------------------------
##' [IPEDS/Carnegie Classification Data]
## ---------------------------

# load IPEDS data and merge with the Carnegie Classification

ipeds24 <- read_csv("../data/sources/hd2024.csv")
ipeds_cost <- read_csv("../data/sources/cost1_2024.csv")
#ipeds_schoolsize <- read_csv("../data/sources/ef2024a.csv") #enrollment Fall 2024
carnegie <- read_excel("../data/sources/2025-Public-Data-File.xlsx", sheet = 2)
ic2024 <- read_csv("../data/sources/ic2024.csv") #NM: new
sfa <- read_csv("../data/sources/sfa2324.csv") #NM: new
adm <- read_csv("../data/sources/adm2024.csv") #NM: new
enroll <- read_csv("../data/sources/effy2024.csv") %>%
  filter(EFFYALEV == 3) %>% 
  select(UNITID, EFFYALEV, EFYTOTLT, EFYAIANT, EFYBKAAT, EFYNHPIT, EFYWHITT, EFYHISPT, EFYASIAT) 

#Let's replace this with the size variable in IPEDS (instsize)
# ipeds_schoolsize <- ipeds_schoolsize |> 
#     filter(EFALEVEL == 1) |> #Level of student (1 == all students total)
#     select(UNITID, EFTOTLT) |> #Grand total
#     mutate(size = case_when(
#       EFTOTLT <= 3000 ~ 0,  #small
#       EFTOTLT <= 10000 ~ 1,  #medium
#       EFTOTLT > 10000 ~ 2, #large
#       TRUE ~ NA_real_))

carnegie <- carnegie |> 
  select(unitid, hsi)

#NM: Merged new files
data <- ipeds24 %>% 
  left_join(carnegie, by = c("UNITID" = "unitid")) %>% 
  left_join(ipeds_cost, by = "UNITID") |> 
  #left_join(ipeds_schoolsize, by = "UNITID") %>% #NM:New
  left_join(ic2024, by = "UNITID" ) %>% #NM:New
  left_join(sfa, by = "UNITID") %>% #NM:New
  left_join(adm, by = "UNITID") %>%  #NM:New
  left_join(enroll, by = "UNITID")



# select variables and create a dataset for analysis
x <- data |> 
    rename_all(tolower) |> #converts all column names in a data frame to lowercase
    select(unitid, instnm, city, stabbr, fips, countycd, countynm, cbsa, cbsatype, csa, obereg,
           locale, zip, stabbr, longitud, latitude, 
           control, iclevel, instcat, deggrant, instsize,
           carnegieic, carnegiesaec, carnegiealf, carnegieapm, carnegiersch,
           hbcu, hsi, tribal,
           room, relaffil, distnced, athassoc,
           admssn, applcn, openadmp, loan_a,
           efytotlt, efyaiant, efybkaat, efynhpit, efywhitt, efyhispt, efyasiat)

# assign to "data"
data <- x


```


```{r Create Sample}
x <- data %>% 
  filter(fips <= 56) |>                                  # Keep only 50 states and DC
  filter(cbsa != -2) |>                                 # Remove colleges not located in CBSAs 
  filter(!is.na(control), control != 3) |>              # 3: private for-profit
  filter(!is.na(iclevel), iclevel != 3) |>              # 3: less than 2 years
  filter(!is.na(carnegiealf), carnegiealf != 6) %>%     # 6: graduate-focused
  filter(instcat >= 2 & instcat <= 4)                 # 1: degree-granting, graduate with no undergraduate degrees
                                                        # 5-6: non-degree-granting
  #filter(carnegieapm == 1)                              # Keep only colleges classified as "mixed" undergraduate programs
  

data <- x

```


```{r cleaning}
## ---------------------------
##' [Data Cleaning]
## ---------------------------

x <- data |> 
  mutate(
         public = case_when(
            control == 2 ~ 0,                             # 0: private
            control == 1 ~ 1,                             # 1: public 
            TRUE ~ NA_real_),   
         
         twoyear = case_when(
            iclevel == 1 ~ 0,                             # 0: 4 or more
            iclevel == 2 ~ 1,                             # 1: at least 2 & less than 4
            TRUE ~ NA_real_),     
         
         msi = case_when(                                 # 0: non of them
            hbcu == 1 ~ 1,                                # 1: HBCU
            hsi == 1 ~ 2,                                 # 2: HSI
            tribal == 1 ~ 3,                              # 3: TCU
            hbcu == 2 & hsi == 0 & tribal == 2 ~ 0,
            is.na(hbcu) | is.na(hsi) | is.na(tribal) ~ NA_real_,
            TRUE ~ NA_real_),
         
         rurality = case_when(
            locale %in% c(31,32,33,41,42,43) ~ 0,         # 0: Town + Rural
            locale %in% c(21,22,23) ~ 1,                  # 1: Suburb
            locale %in% c(11,12,13) ~ 2,                  # 2: City
            TRUE ~ NA_real_),        
         
         size = case_when(
           instsize == 1 ~ 0,                             # 0: < 1,000
           instsize == 2 ~ 1,                             # 1: 1,000 - 4,999
           instsize == 3 ~ 2,                             # 1: 5,000 - 9,999
           instsize == 4 ~ 3,                             # 2: 10,000 - 19,999
           instsize == 5 ~ 4,                             # 3: >=20,000
           TRUE ~ NA_real_),

         housing = case_when(
           room == 2 ~ 0,                                 # 0: no housing
           room == 1 ~ 1,                                 # 1: offer housing
           TRUE ~NA_real_),    

         religious = ifelse(relaffil == -2, 0, 1),        # 0: no religious
                                                          # 1: any religious
         
        #We need to remove colleges that offer completely distance education from our sample
          distance = case_when(
           distnced == 2 ~ 0,                             # 0: not completely distanced learning
           distnced == 1 ~ 1,                             # 1: completely distanced learning
           TRUE ~NA_real_),    

         sports = case_when(
           athassoc == 2 ~ 0,                             # 0: not a member
           athassoc == 1 ~ 1,                             # 1: member of National Athletic Association
           TRUE ~NA_real_),    

         loan = case_when(
           is.na(loan_a) ~ NA_real_,
           loan_a <= quantile(loan_a, 0.25, na.rm = TRUE) ~ 0,     # 0: lowest
           loan_a <= quantile(loan_a, 0.50, na.rm = TRUE) ~ 1,     # 1: low 
           loan_a <= quantile(loan_a, 0.75, na.rm = TRUE) ~ 2,     # 2: high
           TRUE ~ 3),                                              # 3: highest
 
# Q. Since MLCA requires variables starting at 0, is it appropriate to divide loan amount into quartiles (0–3)?

         asc = case_when(
           carnegiesaec == 2 ~ 0,                         # 0: Higher Access, Lower Earnings 
           carnegiesaec == 4 ~ 1,                         # 1: Higher Access, Medium Earnings
           carnegiesaec == 6 ~ 2,                         # 2: Higher Access, Higher Earnings
           carnegiesaec == 1 ~ 3,                         # 3: Lower Access, Lower Earnings
           carnegiesaec == 3 ~ 4,                         # 4: Lower Access, Medium Earnings
           carnegiesaec == 5 ~ 5,                         # 5: Lower Access, Higher Earnings
           TRUE ~ NA_real_),

         awardlev = case_when(
           carnegiealf %in% c(1,2,3) ~ 0,                  # 0: associate - baccalaureate
           carnegiealf == 4 ~ 1,                           # 1: undergrad / grad-Master's
           carnegiealf == 5 ~ 2,                           # 2: undergrad / grad-Doctorate 
           TRUE ~ NA_real_),
         
         focus = case_when(
            carnegieapm ==  1 ~ 0,                             #NM- 0: Mixed
            carnegieapm ==  2 ~ 1,                             #NM- 1: Professions
            carnegieapm %in% c(3,4,5,6,7,8,9,10,11,12) ~ 2,  #NM- 2: Special Focus
            TRUE ~ NA_real_),
        
        research = case_when( 
            carnegiersch == -2 ~ 0,                   #NM- 0: No research designation
            carnegiersch == 3 ~ 1,                    #NM- 1: Research Colleges and Universities 
            carnegiersch == 2 ~ 2,                    #NM- 2: High Spending
            carnegiersch == 1 ~ 3,                    #NM- 3: Very High Spending  
            TRUE ~ NA_real_),          
         
         cbsa = as.character(cbsa),
         metropolitan = if_else(
           cbsatype == 2, 1, 0)
       )


data <- x |>
  filter(distance == 0) %>%                       # remove observations with only distance education
  group_by(cbsa) %>% 
  mutate(inst_num = n_distinct(unitid),
         inst_num = as.numeric(inst_num)) %>% 
  ungroup() %>% 
  mutate(admrate = admssn/applcn) %>% 
  mutate(admrate = if_else(openadmp == 1, 1, admrate)) |> 
  mutate(selectivity = case_when(
         admrate == 1 ~ 0,                        #0: open 
         admrate >= 0.75 & admrate < 1 ~ 1,       #1: less selective
         admrate >= 0.40 & admrate < 0.75 ~ 2,    #2: selective
         admrate < 0.40 ~ 3,                      #3: more selective
         TRUE ~ NA_real_),
         i_perc_black = efybkaat/efytotlt,              #Percent of degree-seeking undergrads by race/ethnicity
         i_perc_white = efywhitt/efytotlt,
         i_perc_hisp = efyhispt/efytotlt,
         i_perc_nhpi = (efyaiant + efynhpit)/efytotlt,
         i_perc_asian = efyasiat/efytotlt
         ) %>% 
  rename(region = obereg) %>% 
  mutate(cbsa = as.character(cbsa))
  
```


```{r census/ACS data}
## ---------------------------
##' [Census/ACS Data]
## ---------------------------

land_area <- core_based_statistical_areas(
  cb = TRUE, 
  year = 2024) %>% 
  select(GEOID, ALAND)


census <- get_acs(geography = "cbsa",
                  year = 2024,
                  variables = c("B01003_001E", # Total population
                                "B19013_001E", # Median Household Income in the Past 12 Months
                                "DP03_0119PE", # % families below poverty line
                                "DP03_0005PE", # % unemployed over 16 years old
                                "DP02_0068PE", # % bach or higher
                                "B03002_003E", # total white (alone, not hispanic)
                                "B03002_004E", # total black (alone, not hispanic)
                                "B03002_012E", # total hispanic
                                "B03002_006E", # total asian (alone, not hispanic)
                                "B03002_001E"  # total by ethnicity
                  ),
                  output = "wide") %>% 
  left_join(land_area)


census <- census |>
  mutate(perc_white = B03002_003E/B03002_001E*100,
         perc_black = B03002_004E/B03002_001E*100,
         perc_hisp = B03002_012E/B03002_001E*100,
         perc_asian = B03002_006E/B03002_001E*100,
         tot_pop = B01003_001E/100000,
         pop_density = B01003_001E/(ALAND/2589988.10)) |> #population per sq mile
  rename(perc_ba = DP02_0068PE,
         med_income = B19013_001E,
         perc_pov = DP03_0119PE,
         perc_unemployed = DP03_0005PE) |> 
  select(tot_pop, pop_density, perc_ba,
         med_income, perc_pov, perc_unemployed,
         perc_white, perc_black, perc_hisp, perc_asian,
         GEOID) |> 
  mutate(GEOID = as.character(GEOID))

data <- data |>
  left_join(census, by = c("cbsa" = "GEOID"))

```


```{r Explore dataset}

data_mlca <- data %>% 
  select(unitid, instnm, stabbr, cbsa, metropolitan, region,
         public, twoyear, size, msi, rurality, housing,
         awardlev, research, 
         religious, distance, sports, focus,
         inst_num, selectivity,
         tot_pop, pop_density, perc_ba, med_income, perc_pov, perc_unemployed,
         perc_white, perc_black, perc_hisp, perc_asian,
         i_perc_white, i_perc_black, i_perc_hisp, i_perc_asian) %>% 
  as.data.frame()

describe(data_mlca)

x <- data_mlca %>% 
  drop_na() %>% 
  group_by(cbsa) %>% 
  mutate(
    cbsa_id = cur_group_id()
  ) %>% 
  as.data.frame()

# data_mlca %>% anti_join(x, by = "unitid") %>% View()

data_mlca <- x

```


```{r MCLA setup}



# Variables:
#   Y-        Columns with indicator variables for level 1 class membership (predictors of institution-level classes)
                # public, two_year, size, msi, award level, research, selectivity 
              
#   iT-       Number of lower-level latent classes

#   id_high-  Name of column with higher-level id
                # CBSA

#   iM-       Number of higher-level latent classes

#   Z-        Columns with lower-level covariates (predictors of level 1 class membership)
                # rurality, housing, religious, sports

#   Zh-       Columns with higher-level covariates (predictors of level 2 class membership)
                # Variables- region, number of IHEs, total population, percent bachelors degree, median income, percent poverty, percent white, percent black, percent hispanic, percent asian


# Level-1 indicators: Observed institution characteristics used to define the latent institution classes
# Level-1 covariates: Institution-level predictors that explain class membership
# Level-2 covariates: CBSA-level regional variables that explain differences in institution class probabilities across regions


#indicators
Y <- c("public", "twoyear", "size", "msi", 
       "research", "selectivity", "focus",
       "rurality", "housing", "religious")                
# Remove the "asc" and "loan" variables due to large number of missing observations

Z <- c("awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian")       #level-1 covariates
# Remove the "loan" variable due to large number of missing observations, include avg net price, avg student aid

Zh <- c("region", "metropolitan", "inst_num", "tot_pop", "pop_density", "perc_ba", "med_income", "perc_pov", "perc_unemployed", "perc_white", "perc_black", "perc_hisp", "perc_asian")   #level-2 covariates


# Q. Is this specification reasonable? 
# A. We don't want to drop observations with missing values as it may bias our estimates.


# data_mlca <- data |>
#   tidyr::drop_na(cbsa, all_of(Y), all_of(Z), all_of(Zh)) |>
#   mutate(across(all_of(Y), ~ {
#     vals <- sort(unique(.[!is.na(.)]))
#     match(., vals) - 1
#   })) |>
#   mutate(cbsa = as.character(cbsa)) |>
#   as.data.frame()

#keep complete cases for all indicators and covariates used in MLCA
#recode indicators to consecutive integers starting at 0 as required for MLCA

```


```{r MCLA Level 1}
## ---------------------------
##' [Find the best # of Classes for Level 1]
## ---------------------------
  

set.seed(1234)

#Number of classes at Level 1
lc_l1 <- multiLCA(
  data       = data_mlca,
  Y          = c("public", "twoyear", "size", "msi", 
       "research", "selectivity", "focus",
       "rurality", "housing", "religious"), 
  iT         = 5:10,               # lower-level classes
  Z          = Z,                  # lower-level covariates
  incomplete = TRUE,               # Use FIML estimation to handle missing values
  extout     = TRUE,
  verbose    = TRUE,
  dataout    = TRUE
)

model_selection <- as.data.frame(lc_l1$model_selection)


y <- multiLCA(
  data       = data_mlca,
  Y          = c("public", "twoyear", "size", "msi", 
       "research", "selectivity", "focus",
       "rurality", "housing", "religious"), 
  iT         = 9,               # lower-level classes
  Z          = c("awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian"),                  # lower-level covariates
  incomplete = FALSE,               # Use FIML estimation to handle missing values
  extout     = FALSE,
  verbose    = TRUE,
  dataout    = TRUE
)

```


```{r Estimate multilevel lca}


lc_l2 <- multiLCA(
  data = data_mlca,
  Y              = Y,
  iT             = 6:12,
  Z              = Z,
  iM             = 2:5,
  id_high        = c("cbsa_id"),
  Zh             = Zh,
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE
)

lc_l2
summary(lc_l2)
plot(lc_l2)


```


```{r}

 #Predicted lower-level class conditional on institutional characteristics
# predicted_class <- multinom( "awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian",data = lc_l2)

data_mlca$.row_id <- seq_len(nrow(data_mlca))

optimal_model <- multiLCA(
  data = data_mlca,
  Y              = c("public", "twoyear", "size", "msi",
       "research", "selectivity", "focus",
       "rurality", "housing", "religious"),
  iT             = 9,
  # Z              = c("awardlev", "sports", "i_perc_white", "i_perc_black", "i_perc_hisp", "i_perc_asian"),
  iM             = 4,
  id_high        = c("cbsa_id"),
  # Zh             = c("region", "metropolitan", "inst_num", "tot_pop", "pop_density", "perc_ba", "med_income", "perc_pov", "perc_unemployed", "perc_white", "perc_black", "perc_hisp", "perc_asian"),
  incomplete     = FALSE,
  extout         = TRUE,
  verbose        = TRUE,
  sequential     = TRUE,
  reord          = FALSE,
  dataout        = TRUE
)


```



```{r Multinomial logistic regression}

reg_data <- as.data.frame(optimal_model[["mPW_N"]]) %>% 
  mutate(pred_class2 = case_when(
    G1 == pmax(G1, G2, G3, G4) ~ "G1",
    G2 == pmax(G1, G2, G3, G4) ~ "G2",
    G3 == pmax(G1, G2, G3, G4) ~ "G3",
    G4 == pmax(G1, G2, G3, G4) ~ "G4"),
    class_prob = case_when(
      pred_class2 == "G1" ~ G1,
      pred_class2 == "G2" ~ G2,
      pred_class2 == "G3" ~ G3,
      pred_class2 == "G4" ~ G4,
    )) %>% 
  select(cbsa_id, pred_class2, class_prob) %>% 
  right_join(data_mlca, by = "cbsa")

multinom(pred_class2 ~ region + metropolitan + inst_num + tot_pop + pop_density + perc_ba + med_income + perc_pov + perc_unemployed + perc_white + perc_black + perc_hisp + perc_asian + class_prob,
              data = reg_data, 
              weights = class_prob)

```

